CHAPTER_PREFIX=\
 chapters/preface/update.md\
 chapters/preface/preface.md\
 chapters/preface/contributors.md\
 ./README.md\
# chapters/todo.md\
# todo.md\
# chapters/preface/issues.md

CHAPTER_DOC=\
 chapters/doc/SECTION.md\
 chapters/doc/plagiarism.md\
 chapters/doc/emacs.md\
 chapters/doc/markdown.md\
 chapters/doc/report.md\
 chapters/doc/type.md


CHAPTER_DRAFT=\
 chapters/SECTION-DRAFT.md

GRAPHICS=\
 chapters/doc/graphviz.md

ART=\
 chapters/art/sentient.md
 
CHAPTER_IN=\
 chapters/linux/ssh-futuresystems.md\
 chapters/in/ansible.md\
 chapters/in/assignments.md\
 chapters/in/box.md\
 chapters/in/cm-hadoop.md\
 chapters/in/course1.md\
 chapters/in/datasets.md\
 chapters/in/futuresystems.md\
 chapters/in/hadoop-comet.md\
 chapters/in/hadoop-rdma.md\
 chapters/in/hadoop-ubunto.md\
 chapters/in/old.md\
 chapters/in/pyenv-anaconda.md\
 chapters/in/python-cmd.md\
 chapters/in/ubuntu.md\
 chapters/in/virtualbox.md\
 chapters/in/vis.md\
 chapters/in/wordcount.md

######################################################################
# i523
######################################################################

CHAPTER_BIGDATA=\
 chapters/class/SECTION.md\
 chapters/class/fall2018.md\
 chapters/bigdata/SECTION.md\
 chapters/bigdata//applications/overview.md\
 chapters/bigdata//applications/physics.md\
 chapters/bigdata//applications/lifestyle.md\
 chapters/bigdata//applications/sport.md\
 chapters/bigdata//applications/cloud.md\
 chapters/bigdata//applications/usecases.md\
 chapters/bigdata//applications/sensor.md\
 chapters/bigdata//applications/web.md\
 chapters/bigdata//applications/health.md\
 chapters/bigdata//algorithms/technology.md\
 chapters/bigdata//algorithms/clustering.md\
 chapters/bigdata//algorithms/plotviz.md\


CHAPTER_OTHER=\
 chapters/icloud//course/old-fundamentals.md\
 chapters/icloud//course/iot.md\
 chapters/icloud//course/nosql.md\
 chapters/icloud//course/fundamentals.md\
 chapters/icloud//course/iaas.md\
 chapters/icloud//course/iterative-mapreduce.md\
 chapters/icloud//course/mapreduce.md\
 chapters/icloud//course/selected.draft.md\
 chapters/icloud//course/nosql-new.md\
 chapters/icloud//course/saas.md\
 chapters/icloud//project2.md\
 chapters/icloud//participation.md\
 chapters/icloud//assignment/assignment.md\
 chapters/icloud//assignment/exercise5/exercise5.md\
 chapters/icloud//assignment/exercise2/exercise2.md\
 chapters/icloud//assignment/exercise2/pagerank.md\
 chapters/icloud//assignment/exercise3/exercise3.md\
 chapters/icloud//assignment/exercise4/exercise4.md\
 chapters/icloud//assignment/exercise8/exercise8.md\
 chapters/icloud//assignment/exercise1/exercise1.md\
 chapters/icloud//assignment/exercise6/exercise6.md\
 chapters/icloud//assignment/exercise7/exercise7.md\
 chapters/icloud//assignment/deprecated/exercise-old7/exercise7.md\
 chapters/icloud//syllabus.md\
 chapters/icloud//preface.md\
 chapters/icloud//deprecated.md\
 chapters/icloud//evaluation.md




######################################################################
# chameleon
######################################################################

CHAPTER_CHAMELEON=\
 chapters/cloud/chameleon/baremetal.md\
 chapters/cloud/chameleon/resources.md\
 chapters/cloud/chameleon/faq-orig.md\
 chapters/cloud/chameleon/hardware.md\
 chapters/cloud/chameleon/cli.md\
 chapters/cloud/chameleon/faq.md\
 chapters/cloud/chameleon/user-guide.md\
 chapters/cloud/chameleon/heat.md\
 chapters/cloud/chameleon/start.md\
 chapters/cloud/chameleon/faq-orig.md\
 chapters/cloud/chameleon/horizon.md\
 chapters/cloud/chameleon/baremetal.md\
 chapters/cloud/chameleon/charge.md\

OLD=\
 chapters/cloud/iot.md\
 chapters/cloud/nosql.md\
 chapters/cloud/assignment/index.md\
 chapters/cloud/fundamentals.md\
 chapters/cloud/iaas.md\
 chapters/cloud/iterative-mapreduce.md\
 chapters/cloud/evaluation/index.md\
 chapters/cloud/mapreduce.md\
 chapters/cloud/participation/index.md\
 chapters/cloud/saas.md\


TWISTER=\
 chapters/mapreduce/twister-installation.md\
 chapters/mapreduce/twister.md\
 chapters/mapreduce/twister2-example.md\
 chapters/mapreduce/harp.md\

MAPREDUCE=\
 chapters/hadoop/hadoop-installation.md\
 chapters/mapreduce/hadoop-installation.md\
 chapters/mapreduce/hadoop-lectures.md\
 chapters/mapreduce/spark-installation.md\
 chapters/mapreduce/spark-lectures.md\
 chapters/mapreduce/spark-streaming.md\
 chapters/new/go.md\
 chapters/new/amqp.md\
 chapters/new/osx-tricks.md\
 chapters/faas/introduction.md\
 chapters/data/formats.md\
 chapters/ai/ai.md\
 chapters/devops/devops.md\
 chapters/devops/travis.md\
 chapters/container/container.md\
 chapters/container/docker-fs.md\
 chapters/container/docker-hadoop-cluster.md\
 chapters/container/docker-hadoop.md\
 chapters/container/docker-hadoop3.md\
 chapters/container/docker-intro.md\
 chapters/container/docker-local.md\
 chapters/container/docker-pagerank-example-instruction.md\
 chapters/container/docker-rest.md\
 chapters/container/docker-spark.md\
 chapters/container/docker-swarm.md\
 chapters/container/exercise.md\
 chapters/container/glossary.md\
 chapters/container/index.md\
 chapters/container/kubernetes-fs.md\
 chapters/container/kubernetes-intro.md\
 chapters/container/qemu.md\
 chapters/iot/dexter.md\
 chapters/iot/easyplug.md\
 chapters/iot/esp8266.md\
 chapters/iot/fundamentals.md\
 chapters/iot/grovepi.md\
 chapters/iot/hardware.md\
 chapters/iot/introduction.md\
 chapters/iot/pi.md\
 chapters/iot/projects.md\
 chapters/iot/sensors.md\
 chapters/iot/tools.md\
 chapters/iot/turtle.md\
 chapters/msg/mqtt.md\
 chapters/msg/graphql.md\
 chapters/rest/rest.md\
 chapters/rest/swagger-bravado.md\
 chapters/rest/swagger-codegen.md\
 chapters/rest/swagger-spec.md\
 chapters/rest/swagger.md\

CHAPTER_PYTHON=\
 chapters/prg/SECTION-PYTHON.md\
 chapters/prg/python.md\
 chapters/prg/python-install.md\
 chapters/prg/python-cloudmesh.md\
 chapters/prg/python-matplotlib.md\
 chapters/prg/python-editor.md\
 chapters/prg/python-libraries.md\
 chapters/prg/python-cmd5.md\
 chapters/prg/python-click.md\
 chapters/prg/python-big-data.md\
 chapters/prg/python-intro.md\
 chapters/prg/python-interactive.md\
 chapters/prg/python-data.md\
 chapters/prg/python-libcloud.md\
 chapters/references.md

DEPRECATED=\
 chapters/linux/ssh2.md

REVIEW=\
 chapters/pi/software2.md

DRAFT=\
 chapters/pi/kubernetes/pi-kubernetes.md\
 chapters/pi/kubernetes/526/readme-kube.md\
 chapters/pi/kubernetes/417/pi-kubernetes.md\


CHAPTER_PI=\
 chapters/SECTION-PREFACE.md\
    chapters/pi/preface.md\
    chapters/preface/notation.md\
    chapters/preface/contributors.md\
    chapters/preface/contributing.md\
    chapters/preface/git.md\
    chapters/preface/exercises.md\
 chapters/preface/outline.md\
 chapters/pi/board.md\
 chapters/pi/case.md\
     chapters/case/case.md\
     chapters/pi/links.md\
 chapters/pi/exercise.md\
 chapters/login-node.md\
     chapters/os/ubuntu-usb-osx.md\
 chapters/SECTION-ONE-PI.md\
     chapters/sd-card.md\
     chapters/pi/software.md\
     chapters/linux/linux.md\
     chapters/linux/ssh.md\
     chapters/linux/refcards.md\
     chapters/pi/config-display.md\
     chapters/pi/vnc.md\
     chapters/pi/motherboard-led.md\
     chapters/run-at-boot.md\
 chapters/clusters/pi-docker.md


OTHER=\
 chapters/SECTION-DRAFT.md\
 chapters/clusters/pi-now.md\
 chapters/pi/setup.md\
 chapters/modify-pi-image.md\
 chapters/pi/pi-passwordreset.md\
 chapters/clusters/pxe.md\
 chapters/clusters/pi-configure-cluster.md\
 chapters/clusters/pi-spark.md\
 chapters/pi/slurm.md\
 chapters/SECTION-hadoop.md\
 chapters/SECTION-yarn.md\
 chapters/SECTION-spark.md\


# $(CHAPTER_BIGDATA)
# $(CHAPTER_PI)

INDEX_OTHER=\
 $(OTHER)\
 $(MAPREDUCE)\
 $(CHAPTER_PYTHON)\
 $(CHAPTER_REFERENCES)


X=\
	$(CHAPTER_OTHER) \
	$(CHAPTER_PYTHON) \
  $(CHAPTER_IN) \
  $(CHAPTER_BIGDATA)
  
other:
ifeq ($(OS), osx)
	cd dest; iconv -t utf-8 $(INDEX_OTHER) > all.md
endif
ifeq ($(OS), linux)
	cd dest; cat $(INDEX_OTHER) > all.md
endif
	cd dest; pandoc $(RESOURCE) $(MARKDOWN-OPTIONS)  $(FORMAT) $(FONTS) $(BIB)  $(CSL) $(CSS) -o $(FILENAME)-other.epub metadata.txt all.md

dot:
	dot -Tpng ../chapters/class/graph-all.dot -o ../chapters/class/images/graph-all.png
	dot -Tpng ../chapters/class/graph-e222.dot -o ../chapters/class/images/graph-e222.png
	dot -Tpng ../chapters/class/graph-i523.dot -o ../chapters/class/images/graph-i523.png
	dot -Tpng ../chapters/class/graph-i524.dot -o ../chapters/class/images/graph-i524.png
	dot -Tpng ../chapters/class/graph-e516.dot -o ../chapters/class/images/graph-e516.png

