all:
	cd 222; make
	cd 516; make
	cd 516; make proceedings
	cd big-data-applications; make
	cd chameleon; make
	cd cloud; make
	cd communicate; make
	cd data-science; make
	cd draft; make
	cd linux; make
	cd pi; make
	cd python; make
	cd writing; make

broken:
	cd proceedings-fa2018; make
