# include ../Makefile.sections
BOOK=BOOK_FA18


FILENAME=vonLaszewski-proceedings-fa18

include ../Makefile.book

proc: setup
	make -f Makefile

setup:
	mkdir -p ../chapters/hid-sp18-709/project-paper
	cp ../../hid-sp18-709/project-paper/report.md ../chapters/hid-sp18-709/project-paper
	cp ../../hid-sp18-709/project-paper/report.bib ../bib/hid-sp18-709-report-refernces.bib
	mkdir -p ../chapters/fa18-516-18/project-paper
	cp ../../fa18-516-18/project-paper/report.md ../chapters/fa18-516-18/project-paper
	cp ../../fa18-516-18/project-paper/report.bib ../bib/fa18-516-18-report-refernces.bib
	mkdir -p ../chapters/fa18-516-11/project-paper
	cp ../../fa18-516-11/project-paper/report.md ../chapters/fa18-516-11/project-paper
	cp ../../fa18-516-11/project-paper/report.bib ../bib/fa18-516-11-report-refernces.bib
