
# ./dest/chapters/preface-old/spring2018.md\

#
# COMPLETED
#
CHAPTER_CLASS=\
 ./dest/chapters/class/SECTION.md\
 ./dest/chapters/class/fall2018.md\
 ./dest/chapters/class/organization.md\
 ./dest/chapters/class/syllabus.md\
 ./dest/chapters/class/policy.md\
 ./dest/chapters/class/assignments.md\
 ./dest/chapters/class/grading.md\
 ./dest/chapters/class/project-ideas.md


CHAPTER_DRAFT=\
 ./dest/chapters/SECTION-DRAFT.md\

GRAPHICS=\
 ./dest/chapters/doc/graphviz.md\

CHAPTER_IN=\
 ./dest/chapters/in/ansible.md\
 ./dest/chapters/in/assignments.md\
 ./dest/chapters/in/box.md\
 ./dest/chapters/in/cm-hadoop.md\
 ./dest/chapters/in/course1.md\
 ./dest/chapters/in/datasets.md\
 ./dest/chapters/in/futuresystems.md\
 ./dest/chapters/in/hadoop-comet.md\
 ./dest/chapters/in/hadoop-rdma.md\
 ./dest/chapters/in/hadoop-ubunto.md\
 ./dest/chapters/in/linux.md\
 ./dest/chapters/in/old.md\
 ./dest/chapters/in/pyenv-anaconda.md\
 ./dest/chapters/in/python-cmd.md\
 ./dest/chapters/in/refcards.md\
 ./dest/chapters/in/ssh.md\
 ./dest/chapters/in/ubuntu.md\
 ./dest/chapters/in/virtualbox.md\
 ./dest/chapters/in/vis.md\
 ./dest/chapters/in/wordcount.md

CHAPTER_BIGDATA=\
 ./dest/chapters/bigdata/SECTION.md\
 ./dest/chapters/bigdata//algorithms/technology.md\
 ./dest/chapters/bigdata//algorithms/clustering.md\
 ./dest/chapters/bigdata//algorithms/plotviz.md\
 ./dest/chapters/bigdata//applications/overview.md\
 ./dest/chapters/bigdata//applications/physics.md\
 ./dest/chapters/bigdata//applications/lifestyle.md\
 ./dest/chapters/bigdata//applications/sport.md\
 ./dest/chapters/bigdata//applications/cloud.md\
 ./dest/chapters/bigdata//applications/usecases.md\
 ./dest/chapters/bigdata//applications/sensor.md\
 ./dest/chapters/bigdata//applications/web.md\
 ./dest/chapters/bigdata//applications/health.md\


CHAPTER_OTHER=\
 ./dest/chapters/icloud//course/old-fundamentals.md\
 ./dest/chapters/icloud//course/iot.md\
 ./dest/chapters/icloud//course/nosql.md\
 ./dest/chapters/icloud//course/fundamentals.md\
 ./dest/chapters/icloud//course/iaas.md\
 ./dest/chapters/icloud//course/iterative-mapreduce.md\
 ./dest/chapters/icloud//course/mapreduce.md\
 ./dest/chapters/icloud//course/selected.draft.md\
 ./dest/chapters/icloud//course/nosql-new.md\
 ./dest/chapters/icloud//course/saas.md\
 ./dest/chapters/icloud//project2.md\
 ./dest/chapters/icloud//participation.md\
 ./dest/chapters/icloud//assignment/assignment.md\
 ./dest/chapters/icloud//assignment/exercise5/exercise5.md\
 ./dest/chapters/icloud//assignment/exercise2/exercise2.md\
 ./dest/chapters/icloud//assignment/exercise2/pagerank.md\
 ./dest/chapters/icloud//assignment/exercise3/exercise3.md\
 ./dest/chapters/icloud//assignment/exercise4/exercise4.md\
 ./dest/chapters/icloud//assignment/exercise8/exercise8.md\
 ./dest/chapters/icloud//assignment/exercise1/exercise1.md\
 ./dest/chapters/icloud//assignment/exercise6/exercise6.md\
 ./dest/chapters/icloud//assignment/exercise7/exercise7.md\
 ./dest/chapters/icloud//assignment/deprecated/exercise-old7/exercise7.md\
 ./dest/chapters/icloud//syllabus.md\
 ./dest/chapters/icloud//preface.md\
 ./dest/chapters/icloud//deprecated.md\
 ./dest/chapters/icloud//evaluation.md\
 ./dest/chapters/art/sentient.md\
 ./dest/chapters/cloud/chameleon/baremetal.md\
 ./dest/chapters/cloud/chameleon/resources.md\
 ./dest/chapters/cloud/chameleon/faq-orig.md\
 ./dest/chapters/cloud/chameleon/hardware.md\
 ./dest/chapters/cloud/chameleon/cli.md\
 ./dest/chapters/cloud/chameleon/faq.md\
 ./dest/chapters/cloud/chameleon/user-guide.md\
 ./dest/chapters/cloud/chameleon/heat.md\
 ./dest/chapters/cloud/chameleon/start.md\
 ./dest/chapters/cloud/chameleon/faq-orig.md\
 ./dest/chapters/cloud/chameleon/horizon.md\
 ./dest/chapters/cloud/chameleon/baremetal.md\
 ./dest/chapters/cloud/chameleon/charge.md\
 ./dest/chapters/cloud/iot.md\
 ./dest/chapters/cloud/nosql.md\
 ./dest/chapters/cloud/assignment/index.md\
 ./dest/chapters/cloud/fundamentals.md\
 ./dest/chapters/cloud/iaas.md\
 ./dest/chapters/cloud/iterative-mapreduce.md\
 ./dest/chapters/cloud/evaluation/index.md\
 ./dest/chapters/cloud/mapreduce.md\
 ./dest/chapters/cloud/participation/index.md\
 ./dest/chapters/cloud/saas.md\
 ./dest/chapters/hadoop/hadoop-installation.md\
 ./dest/chapters/mapreduce/hadoop-installation.md\
 ./dest/chapters/mapreduce/hadoop-lectures.md\
 ./dest/chapters/mapreduce/harp.md\
 ./dest/chapters/mapreduce/spark-installation.md\
 ./dest/chapters/mapreduce/spark-lectures.md\
 ./dest/chapters/mapreduce/spark-streaming.md\
 ./dest/chapters/mapreduce/twister-installation.md\
 ./dest/chapters/mapreduce/twister.md\
 ./dest/chapters/mapreduce/twister2-example.md\
 ./dest/chapters/os/ubuntu-usb-osx.md\
 ./dest/chapters/new/go.md\
 ./dest/chapters/new/amqp.md\
 ./dest/chapters/new/osx-tricks.md\
 ./dest/chapters/faas/introduction.md\
 ./dest/chapters/data/formats.md\
 ./dest/chapters/ai/ai.md\
 ./dest/chapters/devops/devops.md\
 ./dest/chapters/devops/travis.md\
 ./dest/chapters/container/container.md\
 ./dest/chapters/container/docker-fs.md\
 ./dest/chapters/container/docker-hadoop-cluster.md\
 ./dest/chapters/container/docker-hadoop.md\
 ./dest/chapters/container/docker-hadoop3.md\
 ./dest/chapters/container/docker-intro.md\
 ./dest/chapters/container/docker-local.md\
 ./dest/chapters/container/docker-pagerank-example-instruction.md\
 ./dest/chapters/container/docker-rest.md\
 ./dest/chapters/container/docker-spark.md\
 ./dest/chapters/container/docker-swarm.md\
 ./dest/chapters/container/exercise.md\
 ./dest/chapters/container/glossary.md\
 ./dest/chapters/container/index.md\
 ./dest/chapters/container/kubernetes-fs.md\
 ./dest/chapters/container/kubernetes-intro.md\
 ./dest/chapters/container/qemu.md\
 ./dest/chapters/iot/dexter.md\
 ./dest/chapters/iot/easyplug.md\
 ./dest/chapters/iot/esp8266.md\
 ./dest/chapters/iot/fundamentals.md\
 ./dest/chapters/iot/grovepi.md\
 ./dest/chapters/iot/hardware.md\
 ./dest/chapters/iot/introduction.md\
 ./dest/chapters/iot/pi.md\
 ./dest/chapters/iot/projects.md\
 ./dest/chapters/iot/sensors.md\
 ./dest/chapters/iot/tools.md\
 ./dest/chapters/iot/turtle.md\
 ./dest/chapters/iot/vnc.md\
 ./dest/chapters/msg/mqtt.md\
 ./dest/chapters/msg/graphql.md\
 ./dest/chapters/rest/rest.md\
 ./dest/chapters/rest/swagger-bravado.md\
 ./dest/chapters/rest/swagger-codegen.md\
 ./dest/chapters/rest/swagger-spec.md\
 ./dest/chapters/rest/swagger.md\

CHAPTER_PYTHON=\
 ./dest/chapters/prg/SECTION-PYTHON.md\
 ./dest/chapters/prg/python.md\
 ./dest/chapters/prg/python-install.md\
 ./dest/chapters/prg/python-cloudmesh.md\
 ./dest/chapters/prg/python-matplotlib.md\
 ./dest/chapters/prg/python-editor.md\
 ./dest/chapters/prg/python-libraries.md\
 ./dest/chapters/prg/python-cmd5.md\
 ./dest/chapters/prg/python-click.md\
 ./dest/chapters/prg/python-big-data.md\
 ./dest/chapters/prg/python-intro.md\
 ./dest/chapters/prg/python-interactive.md\
 ./dest/chapters/prg/python-data.md\
 ./dest/chapters/prg/python-libcloud.md\
 ./dest/chapters/login-node.md\
 ./dest/chapters/raspberry/README.md\
 ./dest/chapters/sd-card.md\
 ./dest/chapters/linux.md\
 ./dest/chapters/ssh/ssh.md\
 ./dest/chapters/raspberry/config-display.md\
 ./dest/chapters/raspberry/motherboard-led.md\
 ./dest/chapters/run-at-boot.md\
 ./dest/chapters/clusters/pi-now.md\
 ./dest/chapters/modify-pi-image.md\
 ./dest/chapters/pi/pi-passwordreset.md\
 ./dest/chapters/clusters/pxe.md\
 ./dest/chapters/clusters/pi-assemble-cluster.md\
 ./dest/chapters/clusters/pi-configure-cluster.md\
 ./dest/chapters/clusters/pi-docker.md\
 ./dest/chapters/clusters/pi-dockerswarm.md\
 ./dest/chapters/clusters/kubernetes-526/readme-kube.md\
 ./dest/chapters/clusters/kubernetes-417/pi-kubernetes.md\
 ./dest/chapters/clusters/pi-spark.md\
 ./dest/chapters/clusters/pi-software.md\
 ./dest/chapters/pi/slurm.md\
 ./dest/chapters/pi/setup.md\
 ./dest/chapters/pi/software.md\
 ./dest/chapters/pi/case.md\
 ./dest/chapters/references.md

CHAPTER_REFERNCES=\
 ./dest/chapters/references.md

INDEX=\
  $(CHAPTER_DRAFT)\
  $(CHAPTER_OTHER) 

INDEX=\
  $(CHAPTER_PREFIX)\
  $(CHAPTER_CLASS) \
  $(CHAPTER_DOC)\
  $(CHAPTER_SERVICES) \
  $(CHAPTER_REFERENCES) \





X=\
	$(CHAPTER_OTHER) \
	$(CHAPTER_PYTHON) \
  $(CHAPTER_IN) \
  $(CHAPTER_BIGDATA)

MARKDOWN-OPTIONS=-F mermaid-filter -f markdown+smart -f markdown+emoji --indented-code-classes=bash,python,yaml
CSL=--csl=template/ieee-with-url.csl
FORMAT=--toc --number-sections
FONTS=--epub-embed-font='fonts/*.ttf'
BIB=--bibliography dest/references.bib
CSS=--css=template/epub.css
RESOURCE=--resource-path=".:chapters/prg:chapters/iot:chapters/container:chapters/os:chapters/mapreduce:chapters/cloud/chameleon:chapters/doc:chapters/preface:chapters/class"
FILENAME=vonlaszewski-cloud-cluster

#	pandoc ./chapters/prg/python.md -o dest/chapters/prg/python.md --base-header-level=2

epub: dot references todo
	mkdir -p dest/chapters/prg
	bin/markup-all.py
	bin/section.py 1 "Big Data Applications" > dest/chapters/bigdata/SECTION.md
	bin/section.py 1 "Scientific Writing" > dest/chapters/doc/SECTION.md
	bin/section.py 1 "Python" > dest/chapters/prg/SECTION-PYTHON.md
	bin/section.py 1 "Classes" > dest/chapters/class/SECTION.md
	bin/section.py 1 ":construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction:" > dest/chapters/SECTION-DRAFT.md
	pandoc $(RESOURCE) $(MARKDOWN-OPTIONS)  $(FORMAT) $(FONTS) $(BIB)  $(CSL) $(CSS) -o $(FILENAME).epub metadata.txt $(INDEX)

references:
	mkdir -p dest
	cat ../bib/refs-mqtt.bib bib/references.bib ../bib/bibliography.bib > dest/references.bib

html:
	pandoc $(MARKDOWN-OPTIONS)  $(FORMAT) $(FONTS) $(BIB)  $(CSL) -o $(FILENAME).html metadata.txt $(INDEX)

pdf:
	pandoc -f markdown+smart --toc --epub-embed-font='fonts/*.ttf' -V geometry:margin=1in --bibliography references.bib --csl=ieee.csl -o $(FILENAME).pdf metadata.txt $(INDEX)

tex:
	pandoc -f markdown+smart -f markdown+emoji --toc --epub-embed-font='fonts/*.ttf' --bibliography references.bib --csl=ieee.csl -o $(FILENAME).tex metadata.txt $(INDEX)
	pdflatex content.tex


clean:
	rm -rf $(FILENAME).*
	rm -rf dest

list:
	@echo "----"
	@find . -name "*.md"
	@echo "----"
	@echo "Markdown Files": `find . -name "*.md" | wc -l`
	@echo "----"
	@find . -name "*.md"	| sed -e 's/^/ /' | sed 's/$$/\\/'

view:
	open $(FILENAME).epub

todo:
	bin/todo.py > dest/todo.md
	cat dest/todo.md

issues:
	python ../bin/issues.py > /tmp/issues.tex
	pandoc /tmp/issues.tex -o chapters/preface/issues.md
	bin/header.sh chapters/preface/issues.md 3
	head -1 chapters/preface/issues.md > /tmp/issues.md
	echo "<div class=\"smalltable\">" >> /tmp/issues.md
	tail -n +2 chapters/preface/issues.md >> /tmp/issues.md
	echo  >> /tmp/issues.md
	echo "</div>" >> /tmp/issues.md
	echo  >> /tmp/issues.md
	cp /tmp/issues.md chapters/preface/issues.md

dot:
	dot -Tpng chapters/class/graph-all.dot -o chapters/class/images/graph-all.png
	dot -Tpng chapters/class/graph-e222.dot -o chapters/class/images/graph-e222.png
	dot -Tpng chapters/class/graph-i523.dot -o chapters/class/images/graph-i523.png
	dot -Tpng chapters/class/graph-i524.dot -o chapters/class/images/graph-i524.png
	dot -Tpng chapters/class/graph-e516.dot -o chapters/class/images/graph-e516.png

pi:
	make -f Makefile.pi
