# Generated by Django 2.0.2 on 2018-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
